apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: single-mongodb-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10G
  storageClassName: manual